routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// RUTAS REGIONALES
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('regional', 'RegionalController');
Route::get('regional/delete/{id}','RegionalController@delete')->name('regional.delete');
Route::get('regional/restaure/{id}','RegionalController@restore')->name('regional.restore');
//RUTAS CENTROS
Route::resource('centros', 'CentrosController');
Route::get('centros/delete/{id}','CentrosController@delete')->name('centros.delete');
Route::get('centros/restaure/{id}','CentrosController@restore')->name('centros.restore');
//RUTAS RUBLOS
Route::resource('rublos', 'RublosController');
Route::get('rublos/delete/{id}','RublosController@delete')->name('rublos.delete');
Route::get('rublos/restaure/{id}','RublosController@restore')->name('rublos.restore');
//RUTAS LINEAS
Route::resource('lineas', 'LineasController');
Route::get('lineas/delete/{id}','LineasController@delete')->name('lineas.delete');
Route::get('lineas/restaure/{id}','LineasController@restore')->name('lineas.restore');
//AREAS DE CONOCIMIENTO
Route::get('/areas-conocimiento', 'AreasConocimientoController@index')->name('areas.index');
//RUTAS FUNCIONARIOS
Route::resource('funcionarios','FuncionarosController');
Route::get('funcionarios/delete/{id}','FuncionarosController@delete')->name('funcionarios.delete');
Route::get('funcionarios/restaure/{id}','FuncionarosController@restore')->name('funcionarios.restore');
//RUTAS PROYECTOS
Route::resource('proyectos','ProyectosController');
Route::get('proyectos/lista/{tipo}', 'ProyectosController@search')->name('proyectos.search');
Route::get('proyectos/delete/{id}','ProyectosController@delete')->name('proyectos.delete');
Route::get('proyectos/restaure/{id}','ProyectosController@restore')->name('proyectos.restore');

app/Models/Linea.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 21 Feb 2018 19:58:59 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Linea
 *
 * @property int $id
 * @property string $nombre
 * @property int $valor_maximo
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * @property \Illuminate\Database\Eloquent\Collection $rublos
 * @property \Illuminate\Database\Eloquent\Collection $proyectos
 * @package App\Models
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Linea onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereNombre($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Linea whereValorMaximo($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Linea withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Linea withoutTrashed()
 * @mixin \Eloquent
 */
class Linea extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;

	protected $casts = [
		'valor_maximo' => 'int'
	];

	protected $fillable = [
		'nombre',
		'valor_maximo'
	];

	public function rublos()
	{
		return $this->belongsToMany(\App\Models\Rublo::class, 'lineas_rublos', 'lineas_id', 'rublos_id')
					->withPivot('id', 'deleted_at')
					->withTimestamps();
	}

	public function proyectos()
	{
		return $this->hasMany(\App\Models\Proyecto::class, 'lineas_id');
	}
}

app/Http/Controllers/LineasController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\LineasRequest;
use App\Models\Linea;
use App\Models\LineasRublo;
use App\Models\Rublo;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use SebastianBergmann\Diff\Line;


class LineasController extends Controller
{

    public $carpeta_views = "lineas.";
    public $nombre_item = "Linea";

    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index()
    {
        //

        $list = Linea::withTrashed()->paginate(5);
        return view($this->carpeta_views . 'lista', compact([
            'list'
        ]))->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $item = Linea::withoutTrashed()->orderBy('nombre', 'ASC')->get();
        $rublos = Rublo::all();
        return view($this->carpeta_views . 'crear', compact(['item', 'rublos']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(LineasRequest $request)
    {
        //
        $linea = Linea::create($request->all());
        if (count($request->rublos_asociados) > 0) {
            foreach ($request->rublos_asociados as $rublo) {
                $lineaRublo = new LineasRublo();
                $lineaRublo->rublos_id = $rublo;
                $lineaRublo->lineas_id = $linea->id;
                $lineaRublo->save();
                }
        }


        return redirect()->route($this->carpeta_views . 'index')
            ->with('success', $this->nombre_item . ' creado correctamente');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $item = Linea::findOrFail($id);
        return view($this->carpeta_views . 'ver', compact('item'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        $item = Linea::findOrFail($id);
        $rublos = Rublo::all();

        return view($this->carpeta_views . 'editar', compact(['item', 'rublos']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(LineasRequest $request, $id)
    {
        //
        $item = Linea::findOrFail($id);
        $item->update($request->all());

        LineasRublo::where('lineas_id','=', $item->id)->forceDelete();
        if (count($request->rublos_asociados) > 0) {
            foreach ($request->rublos_asociados as $rublo) {
                $lineaRublo = new LineasRublo();
                $lineaRublo->rublos_id = $rublo;
                $lineaRublo->lineas_id = $item->id;
                $lineaRublo->save();
            }
        }
        return redirect()->route($this->carpeta_views . 'index')
            ->with('success', $this->nombre_item . ' actualizado');

    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //

        $item = Linea::findOrFail($id);
        if ($item->delete()) {
            return redirect()->route($this->carpeta_views . 'index')
                ->with('success', $this->nombre_item . " $item->nomnbre ha sido eliminado");
        } else {
            return redirect()->route($this->carpeta_views . 'index')
                ->with('error', $this->nombre_item . " $item->nomnbre no ha podido ser eliminado");
        }
    }

    public function delete($id)
    {
        $item = Linea::findOrFail($id);
        return view($this->carpeta_views . 'eliminar', compact('item'));
    }

    public function restore($id)
    {
        $item = Linea::withTrashed()->where('id', '=', $id)->first();
        if ($item->restore()) {
            return redirect()->route($this->carpeta_views . 'index')
                ->with('success', $this->nombre_item . " $item->nomnbre ha sido restaurado");
        } else {
            return redirect()->route($this->carpeta_views . 'index')
                ->with('error', $this->nombre_item . " $item->nomnbre no ha podido ser restaurado");
        }
    }
}

resources/views/lineas/crear.blade.php
@extends('layouts.dashboard',['nombre'=>'Lineas'])

@section('content')
    {!! Form::open(['route' => 'lineas.store']) !!}
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-8">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Nuevo registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <!-- Regular Input -->
                            <div class="form-group">
                                <label for="codigo" class="control-label">Nombre</label>
                                <input type="text" name="nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="Valor maximo" class="control-label">Valor maximo</label>
                                <input type="text" name="valor_maximo" class="form-control">
                            </div>
                            <label for="codigo" class="control-label">Rublos asociados a la linea</label>
                            <div class="form-group pmd-textfield pmd-textfield-floating-label">
                                <select class="form-control select-tags pmd-select2-tags" name="rublos_asociados[]" multiple>
                                    @foreach($rublos as $reg)
                                        <option value="{{$reg->id}}" @if(old('rublos_asociados')== $reg->id) selected @endif>{{$reg->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <center>
                                    <a class="btn btn-primary" href="{{route('lineas.index')}}">CANCELAR</a>
                                    <button class="btn btn-success" type="submit">GUARDAR</button>
                                </center>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
    {!! Form::close() !!}
@endsection


@section('scripts')
    <script>
        /*$(".select-with-search").select2({
            theme: "bootstrap"
        });*/
        <!-- Select Multiple Tags -->
        $(".select-tags").select2({
            tags: false,
            theme: "bootstrap",
        });
    </script>
@endsection

resources/views/lineas/editar.blade.php
@extends('layouts.dashboard',['nombre'=>'Lineas'])

@section('content')
    {!! Form::model($item, ['method' => 'PATCH','route' => ['lineas.update', $item->id]]) !!}

    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Nuevo registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <!-- Regular Input -->
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Nombre</label>
                                        <input type="text" name="nombre" class="form-control"
                                               value="{{empty(old('nombre')) ? $item->nombre : old('nombre')}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="Valor maximo" class="control-label">Valor maximo</label>
                                        <input type="text" name="valor_maximo" class="form-control" value="{{empty(old('valor_maximo')) ? $item->valor_maximo : old('valor_maximo')}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <label for="codigo" class="control-label">Rublos asociados a la linea</label>
                                    <div class="form-group pmd-textfield pmd-textfield-floating-label">
                                        <select class="form-control select-tags pmd-select2-tags"
                                                name="rublos_asociados[]" multiple>
                                            @foreach($rublos as $reg)

                                                <option value="{{$reg->id}}"
                                                        @php
                                                            foreach ($item->rublos as $r) if($r->id == $reg->id){
                                                             echo 'selected';break;
                                                             }
                                                        @endphp
                                                >{{$reg->nombre}}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <center>
                                            <a class="btn btn-primary" href="{{route('lineas.index')}}">CANCELAR</a>
                                            <button class="btn btn-success" type="submit">GUARDAR</button>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->
            </div>
        </div><!--end Text fields code, example -->
    </div>
    {!! Form::close() !!}
@endsection

@section('scripts')
    <script>
        /*$(".select-with-search").select2({
            theme: "bootstrap"
        });*/
        <!-- Select Multiple Tags -->
        $(".select-tags").select2({
            tags: false,
            theme: "bootstrap",
        });
    </script>
@endsection

resources/views/lineas/eliminar.blade.php
@extends('layouts.dashboard',['nombre'=>'Lineas'])

@section('content')
    {!! Form::model($item, ['method' => 'DELETE','route' => ['lineas.destroy', $item->id]]) !!}

    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Eliminar regitsro</h2>
                            <span class="pmd-card-subtitle-text">
                                Esta a punto de eliminar el registro con la siguiente información:
                            </span>
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <!-- Regular Input -->
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Nombre</label><br>
                                        <b>{{$item->nombre}}</b>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Valor maximo</label><br>
                                        <b>${{number_format($item->valor_maximo)}}</b>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Rublos asociados</label>
                                        <b>
                                            @foreach($item->rublos as $aux)
                                                <li>{{$aux->nombre}}</li>
                                            @endforeach
                                        </b>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <center>
                                        <br>
                                        <b class="text-danger">¿Confirma la eliminación de dicho registro?</b>
                                        <br>
                                        <br>
                                    </center>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <center>
                                            <a class="btn btn-primary" href="{{route('lineas.index')}}">NO,
                                                CANCELAR</a>
                                            <button class="btn btn-success" type="submit">SI, ELIMINAR</button>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->
            </div>
        </div><!--end Text fields code, example -->
    </div>
    {!! Form::close() !!}
@endsection

resources/views/lineas/lista.blade.php
@extends('layouts.dashboard',['nombre'=>'Listado de Lineas'])

@section('content')
    <div class="row">
        <div class="col-md-12" style="margin-bottom: 20px">
            <div class="btn-group">
                <a href="{{route('lineas.create')}}" class="btn pmd-btn-raised pmd-ripple-effect btn-info"
                   type="button">Nuevo registro</a>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- table card code and example -->
        <div class="col-md-12">
            <div class="component-box">

                <!-- Card table example -->
                <div class="pmd-card pmd-z-depth pmd-card-custom-view">
                    <div class="pmd-table-card">
                        <table class="table pmd-table">
                            <thead>
                            <tr class="tr-bold">
                                <th>Nombre</th>
                                <th style="width: 20%">Valor Maximo</th>
                                <th style="width: 40%">Rublos asociados</th>
                                <th style="width: 10%">Fecha Mod.</th>
                                <th style="width: 40px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(count($list)==0)
                                <tr>
                                    <td colspan="5">
                                        <center><br><br><br><b>NO HAY REGISTROS QUE VISUALIZAR</b><br><br><br></center>
                                    </td>
                                </tr>
                            @endif
                            @foreach($list as $row)
                                <tr @if( $row->deleted_at != null ) class="text-danger" @endif >
                                    <td data-title="Nombre">{{{$row->nombre}}}</td>
                                    <td data-title="Valor maximo">${{number_format($row->valor_maximo)}}</td>
                                    <td data-title="Rublos asociados" style="font-size: 0.8em">
                                        @foreach($row->rublos as $i)
                                            <li>{{$i->nombre}}</li>
                                        @endforeach
                                    </td>
                                    <td data-title="Fecha Mod.">{{$row->updated_at}}</td>
                                    <td data-title="">
                                        <span class="dropdown pmd-dropdown clearfix">
												<button class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary"
                                                        type="button" id="dropdownMenuBottomRight"
                                                        data-toggle="dropdown" aria-expanded="true"><i
                                                            class="material-icons pmd-sm">more_vert</i></button>
												<ul aria-labelledby="dropdownMenuDivider" role="menu"
                                                    class="dropdown-menu dropdown-menu-right bg-white">
													<li role="presentation"><a
                                                                href="{{route('lineas.show',[$row->id])}}"
                                                                tabindex="-1"
                                                                role="menuitem">Ver</a></li>
													<li role="presentation"><a
                                                                href="{{route('lineas.edit',$row->id)}}" tabindex="-1"
                                                                role="menuitem">Editar</a></li>
													<li class="divider" role="presentation"></li>
                                                    @if( $row->deleted_at != null )
                                                        <li role="presentation"><a
                                                                    href="{{route('lineas.restore',[$row->id])}}"
                                                                    tabindex="-1"
                                                                    role="menuitem"><span
                                                                        class="text-info">Restaurar</span></a></li>
                                                    @else
                                                        <li role="presentation"><a
                                                                    href="{{route('lineas.delete',[$row->id])}}"
                                                                    tabindex="-1"
                                                                    role="menuitem"><span
                                                                        class="text-danger">Eliminar</span></a></li>
                                                    @endif
												</ul>
											</span>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div> <!-- Card table example end -->

            </div>
        </div> <!-- Card table code and example end -->

    </div>
    <div class="row">
        <div class="col-md-12">
            <br>
            <center>
                {{$list->links()}}
            </center>
        </div>
    </div>
@endsection

@section('extras')

@endsection

resources/views/lineas/ver.blade.php
@extends('layouts.dashboard',['nombre'=>'Lineas'])

@section('content')
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Detalle de la Regional</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <b>Nombre:</b><br>
                                    {{$item->nombre}}
                                </div>
                                <div class="col-md-9">
                                    <b>Valor maximo:</b><br>
                                    {{number_format($item->valor_maximo)}}
                                </div>
                                <div class="row">
                                    <br>
                                </div>
                            </div>
                            <div class="row">
                                <br>
                                <div class="col-md-12">
                                    <b>Rublos asociados a la linea:</b><br>
                                    @foreach($item->rublos as $aux)
                                        <li>{{$aux->nombre}}</li>
                                    @endforeach
                                </div>
                                <div class="row">
                                    <br>
                                </div>
                            </div>
                            <div class="row">
                                <br>
                                <div class="col-md-3">
                                    <b>Estado:</b><br>
                                    {!! $item->deleted_at == null ? '<span class="text-success">ACTIVO</span>' : '<span class="text-danger">ELIMINADO</span>' !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
@endsection