routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// RUTAS REGIONALES
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('regional', 'RegionalController');
Route::get('regional/delete/{id}','RegionalController@delete')->name('regional.delete');
Route::get('regional/restaure/{id}','RegionalController@restore')->name('regional.restore');
//RUTAS CENTROS
Route::resource('centros', 'CentrosController');
Route::get('centros/delete/{id}','CentrosController@delete')->name('centros.delete');
Route::get('centros/restaure/{id}','CentrosController@restore')->name('centros.restore');
//RUTAS RUBLOS
Route::resource('rublos', 'RublosController');
Route::get('rublos/delete/{id}','RublosController@delete')->name('rublos.delete');
Route::get('rublos/restaure/{id}','RublosController@restore')->name('rublos.restore');
//RUTAS LINEAS
Route::resource('lineas', 'LineasController');
Route::get('lineas/delete/{id}','LineasController@delete')->name('lineas.delete');
Route::get('lineas/restaure/{id}','LineasController@restore')->name('lineas.restore');
//AREAS DE CONOCIMIENTO
Route::get('/areas-conocimiento', 'AreasConocimientoController@index')->name('areas.index');
//RUTAS FUNCIONARIOS
Route::resource('funcionarios','FuncionarosController');
Route::get('funcionarios/delete/{id}','FuncionarosController@delete')->name('funcionarios.delete');
Route::get('funcionarios/restaure/{id}','FuncionarosController@restore')->name('funcionarios.restore');
//RUTAS PROYECTOS
Route::resource('proyectos','ProyectosController');
Route::get('proyectos/lista/{tipo}', 'ProyectosController@search')->name('proyectos.search');
Route::get('proyectos/delete/{id}','ProyectosController@delete')->name('proyectos.delete');
Route::get('proyectos/restaure/{id}','ProyectosController@restore')->name('proyectos.restore');

app/Models/Regionale.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 21 Feb 2018 19:58:59 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Regionale
 *
 * @property int $id
 * @property string $nombre
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * @property string $codigo
 * @property \Illuminate\Database\Eloquent\Collection $centros
 * @package App\Models
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Regionale onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereCodigo($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereNombre($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Regionale whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Regionale withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Regionale withoutTrashed()
 * @mixin \Eloquent
 */
class Regionale extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;

	protected $fillable = [
		'nombre',
		'codigo'
	];

	public function centros()
	{
		return $this->hasMany(\App\Models\Centro::class, 'regionales_id');
	}
}

resources/views/regionales/crear.blade.php
@extends('layouts.dashboard',['nombre'=>'Regionales'])

@section('content')
    {!! Form::open(['route' => 'regional.store']) !!}
    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Nuevo registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <!-- Regular Input -->
                            <div class="form-group">
                                <label for="codigo" class="control-label">Código</label>
                                <input type="text" name="codigo" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Nombre</label>
                                <input type="text" name="nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <center>
                                    <a class="btn btn-primary" href="{{route('regional.index')}}">CANCELAR</a>
                                    <button class="btn btn-success" type="submit">GUARDAR</button>
                                </center>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
    {!! Form::close() !!}
@endsection

resources/views/regionales/editar.blade.php
@extends('layouts.dashboard',['nombre'=>'Regionales'])

@section('content')
    {!! Form::model($regional, ['method' => 'PATCH','route' => ['regional.update', $regional->id]]) !!}

    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Nuevo registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <!-- Regular Input -->
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Código</label>
                                        <input type="text" name="codigo" class="form-control"
                                               value="{{empty(old('codigo')) ? $regional->codigo : old('codigo')}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Nombre</label>
                                        <input type="text" name="nombre" class="form-control"
                                               value="{{empty(old('nombre')) ? $regional->nombre : old('nombre')}}">
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <center>
                                            <a class="btn btn-primary" href="{{route('regional.index')}}">CANCELAR</a>
                                            <button class="btn btn-success" type="submit">GUARDAR</button>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->
            </div>
        </div><!--end Text fields code, example -->
    </div>
    {!! Form::close() !!}
@endsection

resources/views/regionales/eliminar.blade.php
@extends('layouts.dashboard',['nombre'=>'Regionales'])

@section('content')
    {!! Form::model($regional, ['method' => 'DELETE','route' => ['regional.destroy', $regional->id]]) !!}

    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Eliminar regitsro</h2>
                            <span class="pmd-card-subtitle-text">
                                Esta a punto de eliminar el registro con la siguiente información:
                            </span>
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <!-- Regular Input -->
                                <div class="col-md-4">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Código</label>
                                        <input type="text" name="codigo" class="form-control"
                                               value="{{empty(old('codigo')) ? $regional->codigo : old('codigo')}}"
                                               readonly>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Nombre</label>
                                        <input type="text" name="nombre" class="form-control"
                                               value="{{empty(old('nombre')) ? $regional->nombre : old('nombre')}}"
                                               readonly>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <center>
                                        <br>
                                        <b class="text-danger">¿Confirma la eliminación de dicho registro?</b>
                                        <br>
                                        <br>
                                    </center>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <center>
                                            <a class="btn btn-primary" href="{{route('regional.index')}}">NO,
                                                CANCELAR</a>
                                            <button class="btn btn-success" type="submit">SI, ELIMINAR</button>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->
            </div>
        </div><!--end Text fields code, example -->
    </div>
    {!! Form::close() !!}
@endsection

resources/views/regionales/lista.blade.php
@extends('layouts.dashboard',['nombre'=>'Regionales'])

@section('content')
    <div class="row">
        <div class="col-md-12" style="margin-bottom: 20px">
            <div class="btn-group">
                <a href="{{route('regional.create')}}" class="btn pmd-btn-raised pmd-ripple-effect btn-info"
                   type="button">Nuevo registro</a>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- table card code and example -->
        <div class="col-md-12">
            <div class="component-box">

                <!-- Card table example -->
                <div class="pmd-card pmd-z-depth pmd-card-custom-view">
                    <div class="pmd-table-card">
                        <table class="table pmd-table">
                            <thead>
                            <tr class="tr-bold">
                                <th style="width: 15%">Código</th>
                                <th>Nombre</th>
                                <th style="width: 10%">No. Centros</th>
                                <th style="width: 10%">Fecha Mod.</th>
                                <th style="width: 40px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(count($list)==0)
                                <tr>
                                    <td colspan="5">
                                        <center><br><br><br><b>NO HAY REGISTROS QUE VISUALIZAR</b><br><br><br></center>
                                    </td>
                                </tr>
                            @endif
                            @foreach($list as $row)
                                <tr @if( $row->deleted_at != null ) class="text-danger" @endif >
                                    <td data-title="Código">{{$row->codigo}}</td>
                                    <td data-title="Nombre">{{{$row->nombre}}}</td>
                                    <td data-title="No. de centros">{{count($row->centros)}}</td>
                                    <td data-title="Fecha Mod.">{{$row->updated_at}}</td>
                                    <td data-title="">
                                        <span class="dropdown pmd-dropdown clearfix">
												<button class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary"
                                                        type="button" id="dropdownMenuBottomRight"
                                                        data-toggle="dropdown" aria-expanded="true"><i
                                                            class="material-icons pmd-sm">more_vert</i></button>
												<ul aria-labelledby="dropdownMenuDivider" role="menu"
                                                    class="dropdown-menu dropdown-menu-right bg-white">
													<li role="presentation"><a href="{{route('regional.show',[$row->id])}}" tabindex="-1"
                                                                               role="menuitem">Ver</a></li>
													<li role="presentation"><a
                                                                href="{{route('regional.edit',$row->id)}}" tabindex="-1"
                                                                role="menuitem">Editar</a></li>
													<li class="divider" role="presentation"></li>
                                                    @if( $row->deleted_at != null )
                                                    <li role="presentation"><a
                                                                href="{{route('regional.restore',[$row->id])}}"
                                                                tabindex="-1"
                                                                role="menuitem"><span
                                                                    class="text-info">Restaurar</span></a></li>
                                                    @else
                                                        <li role="presentation"><a
                                                                    href="{{route('regional.delete',[$row->id])}}"
                                                                    tabindex="-1"
                                                                    role="menuitem"><span
                                                                        class="text-danger">Eliminar</span></a></li>
                                                    @endif
												</ul>
											</span>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div> <!-- Card table example end -->

            </div>
        </div> <!-- Card table code and example end -->

    </div>


    <div class="row">
        <div class="col-md-12">
            <br>
            <center>
                {{$list->links()}}
            </center>
        </div>
    </div>


@endsection

@section('extras')

@endsection

resources/views/regionales/ver.blade.php
@extends('layouts.dashboard',['nombre'=>'Regionales'])

@section('content')
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Detalle de la Regional</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <div class="col-md-3">
                                    <b>Código:</b><br>
                                    {{$regional->codigo}}
                                </div>
                                <div class="col-md-9">
                                    <b>Nombre:</b><br>
                                    {{$regional->nombre}}
                                </div>
                                <div class="row">
                                    <br>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-3">
                                    <b>Estado:</b><br>
                                    {!! $regional->deleted_at == null ? '<span class="text-success">ACTIVO</span>' : '<span class="text-danger">ELIMINADO</span>' !!}
                                </div>
                                <div class="col-md-3">
                                    <b>Fecha de creación:</b><br>
                                    {{$regional->created_at}}
                                </div>
                                <div class="col-md-3">
                                    <b>Fecha ultima modificación:</b><br>
                                    {{$regional->updated_at}}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
@endsection