routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// RUTAS REGIONALES
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('regional', 'RegionalController');
Route::get('regional/delete/{id}','RegionalController@delete')->name('regional.delete');
Route::get('regional/restaure/{id}','RegionalController@restore')->name('regional.restore');
//RUTAS CENTROS
Route::resource('centros', 'CentrosController');
Route::get('centros/delete/{id}','CentrosController@delete')->name('centros.delete');
Route::get('centros/restaure/{id}','CentrosController@restore')->name('centros.restore');
//RUTAS RUBLOS
Route::resource('rublos', 'RublosController');
Route::get('rublos/delete/{id}','RublosController@delete')->name('rublos.delete');
Route::get('rublos/restaure/{id}','RublosController@restore')->name('rublos.restore');
//RUTAS LINEAS
Route::resource('lineas', 'LineasController');
Route::get('lineas/delete/{id}','LineasController@delete')->name('lineas.delete');
Route::get('lineas/restaure/{id}','LineasController@restore')->name('lineas.restore');
//AREAS DE CONOCIMIENTO
Route::get('/areas-conocimiento', 'AreasConocimientoController@index')->name('areas.index');
//RUTAS FUNCIONARIOS
Route::resource('funcionarios','FuncionarosController');
Route::get('funcionarios/delete/{id}','FuncionarosController@delete')->name('funcionarios.delete');
Route::get('funcionarios/restaure/{id}','FuncionarosController@restore')->name('funcionarios.restore');
//RUTAS PROYECTOS
Route::resource('proyectos','ProyectosController');
Route::get('proyectos/lista/{tipo}', 'ProyectosController@search')->name('proyectos.search');
Route::get('proyectos/delete/{id}','ProyectosController@delete')->name('proyectos.delete');
Route::get('proyectos/restaure/{id}','ProyectosController@restore')->name('proyectos.restore');

resources/views/includes/alert-error.blade.php
<div class="static-top col-md-4" id="alert">
    <div class="alert alert-danger" role="alert">
        <button class="btn-link alert-hide" type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-times"></i> </span>
        </button>
        <strong>Upps! Hay algunos problemas en el formulario</strong>
        <span>{{isset($msg) ? $msg : ""}}</span>
        <ul>
            @foreach ($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
</div>

resources/views/includes/alert-success.blade.php
<div class="static-top col-md-4" id="alert">
    <div class="alert alert-success" role="alert">
        <button class="btn-link alert-hide" type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true"><i class="fa fa-times"></i> </span>
        </button>
        <strong>Operación realizada!</strong>
        <span>{{$msg}}</span>
    </div>
</div>

resources/views/includes/confirm-eliminar.blade.php
<div tabindex="-1" class="modal fade" id="alert-dialog" style="display: none;" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-body" id="md-delete-text"></div>
            <div class="pmd-modal-action text-right">
                <button data-dismiss="modal" class="btn pmd-ripple-effect btn-primary pmd-btn-flat" type="button">
                    Save changes
                </button>
                <button data-dismiss="modal" class="btn pmd-ripple-effect btn-default pmd-btn-flat" type="button">
                    Discard
                </button>
            </div>
        </div>
    </div>
</div>

resources/views/includes/menu-lateral.blade.php
@php
    $bgcolor = '#214ebf';
    $name = '';
    if(isset($nombre)){
        $name = $nombre;
        if(strpos(strtolower($nombre), 'regional') !== false){
            $name = 'Regionales';
        }
        else if(strpos(strtolower($nombre), 'centro') !== false){
            $name = 'Centros';
        }
        else if(strpos(strtolower($nombre), 'rublo') !== false){
            $name = 'Rublos';
        }
        else if(strpos(strtolower($nombre), 'regional') !== false){
            $name = 'Regionales';
        }else if(strpos(strtolower($nombre), 'funcionario') !== false){
            $name = 'funcionarios';

        }
        else if(strpos(strtolower($nombre), 'proyecto') !== false){
            $name = 'proyectos';

        }
        else if(strpos(strtolower($nombre), 'lineas') !== false){
            $name = 'Lineas';
        } else if($nombre== "Áreas de conocimiento"){
            $name = 'areasc';
        }
    }
@endphp

<li @if($name=='Inicio') class="fe-selected" @endif >
    <a class="pmd-ripple-effect" href="{{url('/home')}}">
        <i class="media-left media-middle"><i class="fas fa-bars"></i></i>
        <span class="media-body">Inicio</span>
    </a>
</li>

<li class="dropdown pmd-dropdown @if($name == 'Regionales' || $name=="Centros" || $name=='Rublos' || $name=='Lineas' || $name=='areasc') open @endif">
    <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true"
       href="javascript:void(0);">
        <i class="media-left media-middle"><i class="fa fa-cogs"></i></i>
        <span class="media-body">Configuración</span>
        <div class="media-right media-bottom"><i class="dic-more-vert dic"></i></div>
    </a>
    <ul class="dropdown-menu" style="padding: 0">
        <li @if($name=='Regionales') class="fe-selected" @endif ><a href="{{route('regional.index')}}">Regionales</a>
        </li>
        <li @if($name=='Centros') class="fe-selected" @endif ><a href="{{route('centros.index')}}">Centros</a></li>
        <li @if($name=='Rublos') class="fe-selected" @endif><a href="{{route('rublos.index')}}">Rublos</a></li>
        <li @if($name=='Lineas') class="fe-selected" @endif><a href="{{route('lineas.index')}}">Lineas</a></li>
        <li @if($name=='areasc') class="fe-selected" @endif><a href="{{route('areas.index')}}">Áreas de conocimiento</a>
        </li>
        <!--<li><a href="badge.html">Categorias</a></li>-->
    </ul>
</li>

<li @if($name=='funcionarios') class="fe-selected" @endif >
    <a class="pmd-ripple-effect" href="{{route('funcionarios.index')}}">
        <i class="media-left media-middle"><i class="fas fa-bars"></i></i>
        <span class="media-body">Funcionarios</span>
    </a>
</li>

<li class="dropdown pmd-dropdown @if(strpos(strtolower($nombre), 'proyecto') !== false) open @endif">
    <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true"
       href="javascript:void(0);">
        <i class="media-left media-middle"><i class="fas fa-file-archive"></i></i>
        <span class="media-body">Proyectos</span>
        <div class="media-right media-bottom"><i class="dic-more-vert dic"></i></div>
    </a>
    <ul class="dropdown-menu" style="padding: 0">
        <li @if(strtolower($nombre)== "nuevo proyecto") class="fe-selected" @endif ><a href="{{route('proyectos.create')}}">Nuevo
                proyecto</a>
        </li>
        <li @if(strtolower($nombre)== "Listado de proyectos") class="fe-selected" @endif ><a href="{{route('proyectos.search',['tipo'=>'todos'])}}">Listado de
                proyectos</a>
        </li>
        <!--<li><a href="badge.html">Categorias</a></li>-->
    </ul>
</li>

<li class="dropdown pmd-dropdown @if(strpos(strtolower($nombre), 'proyectos') !== false) open @endif">
    <a aria-expanded="false" data-toggle="dropdown" class="btn-user dropdown-toggle media" data-sidebar="true"
       href="javascript:void(0);">
        <i class="media-left media-middle"><i class="fas fa-file-archive"></i></i>
        <span class="media-body">Inventario</span>
        <div class="media-right media-bottom"><i class="dic-more-vert dic"></i></div>
    </a>
    <ul class="dropdown-menu" style="padding: 0">
        <li @if($name=='Regionales') class="fe-selected" @endif ><a href="{{route('regional.index')}}">Nuevo
                elemento</a>
        </li>
        <li @if($name=='areasc') class="fe-selected" @endif><a href="{{route('areas.index')}}">lista de elementos</a>
        </li>
        <li @if($name=='Rublos') class="fe-selected" @endif><a href="{{route('rublos.index')}}">Traslado</a></li>
        </li>
        <!--<li><a href="badge.html">Categorias</a></li>-->
    </ul>
</li>