routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
// RUTAS REGIONALES
Route::get('/home', 'HomeController@index')->name('home');
Route::resource('regional', 'RegionalController');
Route::get('regional/delete/{id}','RegionalController@delete')->name('regional.delete');
Route::get('regional/restaure/{id}','RegionalController@restore')->name('regional.restore');
//RUTAS CENTROS
Route::resource('centros', 'CentrosController');
Route::get('centros/delete/{id}','CentrosController@delete')->name('centros.delete');
Route::get('centros/restaure/{id}','CentrosController@restore')->name('centros.restore');
//RUTAS RUBLOS
Route::resource('rublos', 'RublosController');
Route::get('rublos/delete/{id}','RublosController@delete')->name('rublos.delete');
Route::get('rublos/restaure/{id}','RublosController@restore')->name('rublos.restore');
//RUTAS LINEAS
Route::resource('lineas', 'LineasController');
Route::get('lineas/delete/{id}','LineasController@delete')->name('lineas.delete');
Route::get('lineas/restaure/{id}','LineasController@restore')->name('lineas.restore');
//AREAS DE CONOCIMIENTO
Route::get('/areas-conocimiento', 'AreasConocimientoController@index')->name('areas.index');
//RUTAS FUNCIONARIOS
Route::resource('funcionarios','FuncionarosController');
Route::get('funcionarios/delete/{id}','FuncionarosController@delete')->name('funcionarios.delete');
Route::get('funcionarios/restaure/{id}','FuncionarosController@restore')->name('funcionarios.restore');
//RUTAS PROYECTOS
Route::resource('proyectos','ProyectosController');
Route::get('proyectos/lista/{tipo}', 'ProyectosController@search')->name('proyectos.search');
Route::get('proyectos/delete/{id}','ProyectosController@delete')->name('proyectos.delete');
Route::get('proyectos/restaure/{id}','ProyectosController@restore')->name('proyectos.restore');

app/Models/Funcionario.php
<?php

/**
 * Created by Reliese Model.
 * Date: Wed, 21 Feb 2018 19:58:59 +0000.
 */

namespace App\Models;

use Reliese\Database\Eloquent\Model as Eloquent;

/**
 * Class Funcionario
 *
 * @property int $id
 * @property int $nombre
 * @property int $correo
 * @property int $documento
 * @property int $telefono
 * @property int $tipo_functionarios_id
 * @property int $centros_id
 * @property \Carbon\Carbon $created_at
 * @property \Carbon\Carbon $updated_at
 * @property string $deleted_at
 * @property \App\Models\Centro $centro
 * @property \App\Models\TipoFunctionario $tipo_functionario
 * @property \Illuminate\Database\Eloquent\Collection $items
 * @package App\Models
 * @method static bool|null forceDelete()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Funcionario onlyTrashed()
 * @method static bool|null restore()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereCentrosId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereCorreo($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereDeletedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereDocumento($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereNombre($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereTelefono($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereTipoFunctionariosId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Models\Funcionario whereUpdatedAt($value)
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Funcionario withTrashed()
 * @method static \Illuminate\Database\Query\Builder|\App\Models\Funcionario withoutTrashed()
 * @mixin \Eloquent
 */
class Funcionario extends Eloquent
{
	use \Illuminate\Database\Eloquent\SoftDeletes;

	protected $casts = [
		'nombre' => 'string',
		'correo' => 'string',
		'documento' => 'string',
		'telefono' => 'string',
		'tipo_functionarios_id' => 'int',
		'centros_id' => 'int'
	];

	protected $fillable = [
		'nombre',
		'correo',
		'documento',
		'telefono',
		'tipo_functionarios_id',
		'centros_id'
	];

	public function centro()
	{
		return $this->belongsTo(\App\Models\Centro::class, 'centros_id');
	}

	public function tipo_functionario()
	{
		return $this->belongsTo(\App\Models\TipoFunctionario::class, 'tipo_functionarios_id');
	}

	public function items()
	{
		return $this->belongsToMany(\App\Models\Item::class, 'items_funcionarios', 'funcionarios_id', 'items_id')
					->withPivot('id', 'fecha_asignado', 'fecha_desasignado', 'deleted_at')
					->withTimestamps();
	}
}

resources/views/funcionarios/crear.blade.php
@extends('layouts.dashboard',['nombre'=>'Crear Funcionario'])

@section('content')
    {!! Form::open(['route' => 'funcionarios.store']) !!}
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-8">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Nuevo registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <!-- Regular Input -->
                            <div class="form-group">
                                <label for="codigo" class="control-label">Nombre</label>
                                <input type="text" name="nombre" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">No. de documento</label>
                                <input type="text" name="documento" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Correo electrónico</label>
                                <input type="text" name="correo" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="Valor maximo" class="control-label">Teléfono</label>
                                <input type="text" name="telefono" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Centro de formación asociado</label>
                                <select class="select-with-search form-control pmd-select2" name="centros_id">
                                    @foreach($centros as $reg)
                                        <option value="{{$reg->id}}" @if(old('centros_id')== $reg->id) selected @endif>{{$reg->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Tipo de funcionario</label>
                                <select class="select-with-search form-control pmd-select2" name="tipo_functionarios_id">
                                    @foreach($tipof as $reg)
                                        <option value="{{$reg->id}}" @if(old('tipo_functionarios_id')== $reg->id) selected @endif>{{$reg->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <center>
                                    <a class="btn btn-primary" href="{{route('funcionarios.index')}}">CANCELAR</a>
                                    <button class="btn btn-success" type="submit">GUARDAR</button>
                                </center>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
    {!! Form::close() !!}
@endsection


@section('scripts')
    <script>
        $(".select-with-search").select2({
            theme: "bootstrap"
        });
    </script>
@endsection

resources/views/funcionarios/editar.blade.php
@extends('layouts.dashboard',['nombre'=>'Crear Funcionario'])

@section('content')
    {!! Form::model($item, ['method' => 'PATCH','route' => ['funcionarios.update', $item->id]]) !!}
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-8">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Editar registro</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <!-- Regular Input -->
                            <div class="form-group">
                                <label for="codigo" class="control-label">Nombre</label>
                                <input type="text" name="nombre" class="form-control" value="{{old('nombre')!=null ? old('nombre') : $item->nombre}}">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">No. de documento</label>
                                <input type="text" name="documento" class="form-control" value="{{old('documento')!=null ? old('documento') : $item->documento}}">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Correo electrónico</label>
                                <input type="text" name="correo" class="form-control" value="{{old('correo')!=null ? old('correo') : $item->correo}}">
                            <div class="form-group">
                                <label for="Valor maximo" class="control-label">Teléfono</label>
                                <input type="text" name="telefono" class="form-control" value="{{old('telefono')!=null ? old('telefono') : $item->telefono}}">
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Centro de formación asociado</label>
                                <select class="select-with-search form-control pmd-select2" name="centros_id">
                                    @foreach($centros as $reg)
                                        <option value="{{$reg->id}}" @if(old('centros_id') !=null && old('centros_id')== $reg->id) selected
                                                @elseif(old('centros_id') ==null && $item->centros_id == $reg->id) selected @endif>{{$reg->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Tipo de funcionario</label>
                                <select class="select-with-search form-control pmd-select2" name="tipo_functionarios_id">
                                    @foreach($tipof as $reg)
                                        <option value="{{$reg->id}}" @if($item->tipo_functionarios_id== $reg->id) selected @endif>{{$reg->nombre}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="form-group">
                                <center>
                                    <a class="btn btn-primary" href="{{route('funcionarios.index')}}">CANCELAR</a>
                                    <button class="btn btn-success" type="submit">GUARDAR</button>
                                </center>
                            </div>
                        </div>
                    </div>
                </div>
            </div><!-- end Text fields example -->

        </div>
    </div><!--end Text fields code, example -->
    {!! Form::close() !!}
@endsection


@section('scripts')
    <script>
        $(".select-with-search").select2({
            theme: "bootstrap"
        });
    </script>
@endsection

resources/views/funcionarios/eliminar.blade.php
@extends('layouts.dashboard',['nombre'=>'Funcionario'])

@section('content')
    {!! Form::model($item, ['method' => 'DELETE','route' => ['funcionarios.destroy', $item->id]]) !!}

    <div class="col-md-6">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Eliminar regitsro</h2>
                            <span class="pmd-card-subtitle-text">
                                Esta a punto de eliminar el registro con la siguiente información:
                            </span>
                        </div>
                        <div class="pmd-card-body">
                            <div class="row">
                                <!-- Regular Input -->
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Nombre</label><br>
                                        <b>{{$item->nombre}}</b>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Documento</label><br>
                                        <b>{{number_format($item->documento)}}</b>
                                    </div>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label for="codigo" class="control-label">Centro de formación</label><br>
                                        <b>{{$item->centro->nombre}}</b>
                                    </div>
                                </div>

                                <div class="col-md-12">
                                    <center>
                                        <br>
                                        <b class="text-danger">¿Confirma la eliminación de dicho registro?</b>
                                        <br>
                                        <br>
                                    </center>
                                </div>
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <center>
                                            <a class="btn btn-primary" href="{{route('funcionarios.index')}}">NO,
                                                CANCELAR</a>
                                            <button class="btn btn-success" type="submit">SI, ELIMINAR</button>
                                        </center>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->
            </div>
        </div><!--end Text fields code, example -->
    </div>
    {!! Form::close() !!}
@endsection

resources/views/funcionarios/lista.blade.php
@extends('layouts.dashboard',['nombre'=>'Listado de Funcionarios'])

@section('content')
    <div class="row">
        <div class="col-md-12" style="margin-bottom: 20px">
            <div class="btn-group">
                <a href="{{route('funcionarios.create')}}" class="btn pmd-btn-raised pmd-ripple-effect btn-info"
                   type="button">Nuevo registro</a>
            </div>
        </div>
    </div>
    <div class="row">
        <!-- table card code and example -->
        <div class="col-md-12">
            <div class="component-box">

                <!-- Card table example -->
                <div class="pmd-card pmd-z-depth pmd-card-custom-view">
                    <div class="pmd-table-card">
                        <table class="table pmd-table">
                            <thead>
                            <tr class="tr-bold">
                                <th>Nombre</th>
                                <th style="width: 15%">Correo</th>
                                <th style="width: 10%">Teléfono</th>
                                <th style="width: 40%">Centro de Formación</th>
                                <th style="width: 10%">Fecha mod.</th>
                                <th style="width: 40px"></th>
                            </tr>
                            </thead>
                            <tbody>
                            @if(count($list)==0)
                                <tr>
                                    <td colspan="5">
                                        <center><br><br><br><b>NO HAY REGISTROS QUE VISUALIZAR</b><br><br><br></center>
                                    </td>
                                </tr>
                            @endif
                            @foreach($list as $row)
                                <tr @if( $row->deleted_at != null ) class="text-danger" @endif >
                                    <td data-title="Nombre">{{{$row->nombre}}}</td>
                                    <td data-title="Correo">{{$row->correo}}</td>
                                    <td data-title="Teléfono">{{$row->telefono}}</td>
                                    <td data-title="Centro de Formación" style="font-size: 0.8em">
                                       {{$row->centro->nombre}}
                                    </td>
                                    <td data-title="Fecha Mod.">{{$row->updated_at}}</td>
                                    <td data-title="">
                                        <span class="dropdown pmd-dropdown clearfix">
												<button class="btn btn-sm pmd-btn-fab pmd-btn-flat pmd-ripple-effect btn-primary"
                                                        type="button" id="dropdownMenuBottomRight"
                                                        data-toggle="dropdown" aria-expanded="true"><i
                                                            class="material-icons pmd-sm">more_vert</i></button>
												<ul aria-labelledby="dropdownMenuDivider" role="menu"
                                                    class="dropdown-menu dropdown-menu-right bg-white">
													<li role="presentation"><a
                                                                href="{{route('funcionarios.show',[$row->id])}}"
                                                                tabindex="-1"
                                                                role="menuitem">Ver</a></li>
													<li role="presentation"><a
                                                                href="{{route('funcionarios.edit',$row->id)}}" tabindex="-1"
                                                                role="menuitem">Editar</a></li>
													<li class="divider" role="presentation"></li>
                                                    @if( $row->deleted_at != null )
                                                        <li role="presentation"><a
                                                                    href="{{route('funcionarios.restore',[$row->id])}}"
                                                                    tabindex="-1"
                                                                    role="menuitem"><span
                                                                        class="text-info">Restaurar</span></a></li>
                                                    @else
                                                        <li role="presentation"><a
                                                                    href="{{route('funcionarios.delete',[$row->id])}}"
                                                                    tabindex="-1"
                                                                    role="menuitem"><span
                                                                        class="text-danger">Eliminar</span></a></li>
                                                    @endif
												</ul>
											</span>
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                </div> <!-- Card table example end -->

            </div>
        </div> <!-- Card table code and example end -->

    </div>
    <div class="row">
        <div class="col-md-12">
            <br>
            <center>
                {{$list->links()}}
            </center>
        </div>
    </div>
@endsection

@section('extras')

@endsection

resources/views/funcionarios/ver.blade.php
@extends('layouts.dashboard',['nombre'=>'Funcionarios'])

@section('content')
    <div class="col-md-12">
        <div class="component-box">

            <!-- Text fields example -->
            <div class="row">
                <div class="col-md-12">
                    <div class="pmd-card pmd-z-depth pmd-card-custom-form">
                        <div class="pmd-card-title">
                            <h2 class="pmd-card-title-text">Detalle del funcionario</h2>
                            <!--<span class="pmd-card-subtitle-text">Secondary text</span>-->
                        </div>
                        <div class="pmd-card-body">
                            <div class="form-group">
                                <label for="codigo" class="control-label">Nombre</label>
                                <b><br>{{$item->nombre}}</b>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">No. de documento</label>
                                <b><br>{{$item->documento}}</b>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Correo electrónico</label>
                                <b><br>{{$item->correo}}</b>
                            </div>
                            <div class="form-group">
                                <label for="Valor maximo" class="control-label">Teléfono</label>
                                <b><br>{{$item->telefono}}</b>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Centro de formación asociado</label>
                                <b><br>{{$item->centro->nombre}}</b>
                            </div>
                            <div class="form-group">
                                <label for="codigo" class="control-label">Tipo de funcionario</label>
                                <b><br>{{$item->tipo_functionario->nombre}}</b>
                            </div>
                        </div>
                    </div>
                </div><!-- end Text fields example -->

            </div>
        </div><!--end Text fields code, example -->
@endsection